- name: Installing and Run the Nginx server
  become: true
  hosts: localhost
  tasks:
  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: Run the Nginx
    ansible.builtin.service:
      name: Nginx
      state: started
      enabled: true
