- name: Installing and Run the Nginx server through ansible
  become: true
  hosts: localhost
  tasks:
  - name: Install Nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Run the Nginx
    ansible.builtin.service:
      name: nginx
      state: started  #it will ensure start state
      enabled: yes  #it will run and enabled the nginx service
