- name: Installing and Run the Nginx server through ansible
  become: true
  hosts: localhost
  tasks:
  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
  - name: Run the Nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true  #it will run and enabled the nginx service
