- name: Prompting variables
  become: true
  hosts: localhost
  var:
  -  course: "Devops"
  vars_prompt:
    - name: username
      prompt: "Please enter the USERNAME: "
      private: false

    - name: password
      prompt: "Please enter the PASSWORD: "
      private: true

  tasks:
    - name: Show entered credentials
      ansible.builtin.debug:
        msg: "Hi, your username is {{ username }}, and your password is {{ password }}, {{ course }}"

     