- name: Prompting variables
  become: true
  hosts: localhost
  vars:
    Course: "Devops"
    Name: "shiva"
  vars_prompt:
    - name: username
      prompt: "Please enter the USERNAME: "
      private: false

    - name: password
      prompt: "Please enter the PASSWORD: "
      private: true

  tasks:
    - name: Show entered credentials
      ansible.builtin.debug:
        msg: "Hi, your username is {{ username }}, and your password is {{ password }}"
  tasks:
  -  name: Variables
     ansible.builtin.debug:
       msg: "Im taking the {{ Course }} from {{ Name }}"
  

     