- name: Prompt
  become: true
  hosts: localhost
  vars-prompt:
  - name: Username
    Prompt: "Please enter the USERNAME: "
    private: false
  - name: Password
    Prompt: "Please enter the Password: "
    private: true
  tasks:
  - name: username, password
    ansible.builtin.debug:
    msg: "Hi your username is {{Username}}, Password is {{Password}}"

     
     