- name: Varaibles
  become: true
  hosts: localhost
  vars:
    Course: "Devops"
    Name: "shiva"
    Duration: "120hours"
  tasks:
  -  name: Variables
     ansible.builtin.debug:
       msg: "Im taking the {{Course}} from {{Name}}, The duration is {{Duration}}"